=== inxar/syntacs/etc/grammar.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

 $Id: grammar.dtd,v 1.1.1.1 2001/07/06 09:08:04 pcj Exp $

 Copyright (C) 2001 Paul Cody Johnston - pcj@inxar.org

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or (at
 your option) any later version.

 This program is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 USA.  

-->

<!--
This is the DTD for the Regular and Context-Free grammars.  Using these constructs
one can specify the grammar for a lexer and parser.
-->

<!-- =================================================== -->
<!-- ENTITIES -->
<!-- =================================================== -->
<!-- 
MEMBER ELEMENTS FOR REGULAR EXPRESSIONS:

 char:             a single character  
 string:           a sequence of characters 
 union:            a set of alternatives (called alleles) 
 closure:          an optional cycle (kleene) '*'
 positive-closure: an non-optional cycle (positive-kleene) '+'
 option:           an optional element '?'
 epsilon:          the empty 'string' 
 interval:         a contiguous interval of characters (only in classes) 
 list:             a sequence of members 
 class:            a character class 

-->
<!ENTITY % member "char|string|union|closure|positive-closure|option|list|class|epsilon">

<!-- =================================================== -->
<!-- GRAMMAR ELEMENTS -->
<!-- =================================================== -->

<!-- this is the top-level element -->
<!ELEMENT grammar (property*, context*, terminal+, nonterminal*, match*, reduce*)>
<!ATTLIST grammar
	name CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT context (member*)>
<!ATTLIST context
	name CDATA #REQUIRED
	start (true|false) "false"
>

<!ELEMENT member EMPTY>
<!ATTLIST member
	terminal CDATA #REQUIRED
	action CDATA #IMPLIED
>

<!ELEMENT terminal EMPTY>
<!ATTLIST terminal
	name CDATA #REQUIRED
>

<!ELEMENT nonterminal EMPTY>
<!ATTLIST nonterminal
	name CDATA #REQUIRED
	start (true|false) "false"
>

<!ELEMENT match (%member;)>
<!ATTLIST match
	terminal CDATA #REQUIRED
>

<!ELEMENT reduce (symbol)+>
<!ATTLIST reduce
	nonterminal CDATA #REQUIRED
>

<!ELEMENT symbol EMPTY>
<!ATTLIST symbol
	name CDATA #REQUIRED
>

<!-- =================================================== -->
<!-- REGEXP ELEMENTS -->
<!-- =================================================== -->

<!ELEMENT epsilon EMPTY>

<!ELEMENT char EMPTY>
<!ATTLIST char
	value CDATA #REQUIRED
>

<!ELEMENT interval EMPTY>
<!ATTLIST interval
	lo CDATA #REQUIRED
	hi CDATA #REQUIRED
>

<!ELEMENT string EMPTY>
<!ATTLIST string
	value CDATA #REQUIRED
>

<!ELEMENT class (char|interval)+>
<!ATTLIST class
	negated (true|false) "false"
>

<!ELEMENT list (%member;)+>

<!ELEMENT union (%member;)+>

<!ELEMENT option (%member;)>

<!ELEMENT closure (%member;)>

<!ELEMENT positive-closure (%member;)>

=== inxar/syntacs/grammar/scc/scc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grammar SYSTEM "file:./etc/grammar.dtd">

<grammar name="scc" version="0.0.1">

 <property name="author" value="Paul Cody Johnston"/>
 <property name="author-email" value="pcj@inxar.org"/>
 <property name="compile-dpa-constructor-method" value="LALR1"/>
 <property name="compile-sourcepath" value="./src"/>
 <property name="compile-namespace" value="com.inxar.syntacs.translator.test"/>
 <property name="viz-sourcepath" value="./grammar"/>
 <property name="viz-namespace" value="scc"/>
 <property name="viz-lexical" value="true"/>
 <property name="viz-syntactic" value="true"/>

 <terminal name="c"/>
 <terminal name="d"/>

 <nonterminal name="Goal" start="true"/>
 <nonterminal name="S"/>
 <nonterminal name="C"/>

 <match terminal="c"><char value="c"/></match>
 <match terminal="d"><char value="d"/></match>
 
 <reduce nonterminal="Goal">
  <symbol name="S"/>
 </reduce>

 <reduce nonterminal="S">
  <symbol name="C"/>
  <symbol name="C"/>
 </reduce>

 <reduce nonterminal="C">
  <symbol name="c"/>
  <symbol name="C"/>
 </reduce>

 <reduce nonterminal="C">
  <symbol name="d"/>
 </reduce>

</grammar>

=== inxar/syntacs/grammar/abb/abb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grammar SYSTEM "file:./etc/grammar.dtd">

<grammar name="abb" version="0.0.1">

 <property name="author" value="Paul Cody Johnston"/>
 <property name="author-email" value="pcj@inxar.org"/>
 <property name="compile-sourcepath" value="./src"/>
 <property name="compile-dpa-constructor-method" value="LALR1"/>
 <property name="compile-namespace" value="com.inxar.syntacs.translator.test"/>
 <property name="viz-sourcepath" value="./grammar"/>
 <property name="viz-namespace" value="abb"/>
 <property name="viz-lexical" value="true"/>
 <property name="viz-syntactic" value="true"/>

 <terminal name="abb"/>

 <nonterminal name="Goal" start="true"/>

 <match terminal="abb">
  <list>
   <closure>
    <union>
     <char value="a"/>
     <char value="b"/>
    </union>
   </closure>
   <char value="a"/>
   <char value="b"/>
   <char value="b"/>
  </list>
 </match>

 <reduce nonterminal="Goal">
  <symbol name="abb"/>
 </reduce>

</grammar>

=== inxar/syntacs/grammar/etf/etf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grammar SYSTEM "file:./etc/grammar.dtd">

<grammar name="etf" version="0.0.1">

 <property name="author" value="Paul Cody Johnston"/>
 <property name="author-email" value="pcj@inxar.org"/>
 <property name="compile-dpa-constructor-method" value="LALR1"/>
 <property name="compile-sourcepath" value="./src"/>
 <property name="compile-namespace" value="com.inxar.syntacs.translator.test"/>
 <property name="viz-sourcepath" value="./grammar"/>
 <property name="viz-namespace" value="etf"/>
 <property name="viz-lexical" value="true"/>
 <property name="viz-syntactic" value="true"/>
 <property name="viz-dpa-hide-loopback-edges" value="true"/>

 <terminal name="PLUS"/>
 <terminal name="STAR"/>
 <terminal name="OPRN"/>
 <terminal name="CPRN"/>
 <terminal name="IDENT"/>

 <nonterminal name="Goal" start="true"/>
 <nonterminal name="E"/>
 <nonterminal name="T"/>
 <nonterminal name="F"/>

 <match terminal="PLUS"><char value="+"/></match>
 <match terminal="STAR"><char value="*"/></match>
 <match terminal="OPRN"><char value="("/></match>
 <match terminal="CPRN"><char value=")"/></match>
 <match terminal="IDENT">
  <list>
   <class>
    <char value="_"/>
    <interval lo="a" hi="z"/>
    <interval lo="A" hi="Z"/>
   </class>
   <closure>
    <class>
     <char value="_"/>
     <interval lo="a" hi="z"/>
     <interval lo="A" hi="Z"/>
     <interval lo="0" hi="9"/>
    </class>
   </closure>
  </list>
 </match>
 
 <reduce nonterminal="Goal">
  <symbol name="E"/>
 </reduce>

 <reduce nonterminal="E">
  <symbol name="E"/>
  <symbol name="PLUS"/>
  <symbol name="T"/>
 </reduce>

 <reduce nonterminal="E">
  <symbol name="T"/>
 </reduce>

 <reduce nonterminal="T">
  <symbol name="T"/>
  <symbol name="STAR"/>
  <symbol name="F"/>
 </reduce>

 <reduce nonterminal="T">
  <symbol name="F"/>
 </reduce>

 <reduce nonterminal="F">
  <symbol name="OPRN"/>
  <symbol name="E"/>
  <symbol name="CPRN"/>
 </reduce>

 <reduce nonterminal="F">
  <symbol name="IDENT"/>
 </reduce>

</grammar>

=== inxar/syntacs/grammar/syntacs/syntacs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grammar SYSTEM "file:./etc/grammar.dtd">

<grammar name="syntacs" version="0.1.0">

 <!-- ================================================== -->
 <!-- PROPERTY DEFINITIONS                               -->
 <!-- ================================================== -->

 <property name="author" value="Paul Cody Johnston"/>
 <property name="author-email" value="pcj@inxar.org"/>
 <property name="compile-dpa-constructor-method" value="LALR1"/>
 <property name="compile-sourcepath" value="./src"/>
 <property name="compile-namespace" value="com.inxar.syntacs.translator.syntacs"/>
 <property name="compile-interpreter-classname" 
	value="com.inxar.syntacs.translator.syntacs.SyntacsInterpreter"/>

 <property name="viz-sourcepath" value="./grammar"/>
 <property name="viz-namespace" value="syntacs"/>
 <property name="viz-lexical" value="true"/>
 <property name="viz-syntactic" value="true"/>

 <property name="viz-dpa-size" value="40,40"/>
 <property name="viz-dpa-concentrate-edges" value="true"/>

 <!-- ================================================== -->
 <!-- CONTEXT DEFINITIONS                                -->
 <!-- ================================================== -->

 <!-- this grammar only has the default context -->
 <context name="default" start="true">
  <member terminal="COMMENT"/>
  <member terminal="WHITESPACE"/>
  <member terminal="IDENT"/>
  <member terminal="STRING"/>
  <member terminal="VERSION_STRING"/>
  <member terminal="COMMA"/>
  <member terminal="SEMI"/>
  <member terminal="EQUALS"/>
 </context>

 <!-- ================================================== -->
 <!-- TERMINAL DECLARATIONS                              -->
 <!-- ================================================== -->
 
 <terminal name="COMMENT"/>
 <terminal name="WHITESPACE"/>

 <terminal name="THIS"/>
 <terminal name="IS"/>
 <terminal name="VERSION"/>
 <terminal name="START"/>
 <terminal name="IN"/>
 <terminal name="CONTEXT"/>
 <terminal name="TERMINAL"/>
 <terminal name="NONTERMINAL"/>
 <terminal name="REDUCE"/>
 <terminal name="INCLUDES"/>
 <terminal name="WHEN"/>
 <terminal name="SHIFTS"/>
 <terminal name="UNSHIFTS"/>
 <terminal name="ACCEPT"/>
 <terminal name="PROPERTY"/>
 <terminal name="MATCHES"/>

 <terminal name="IDENT"/>
 <terminal name="STRING"/>
 <terminal name="VERSION_STRING"/>
 <terminal name="COMMA"/>
 <terminal name="SEMI"/>
 <terminal name="EQUALS"/>

 <!-- ================================================== -->
 <!-- NONTERMINAL DECLARATIONS                           -->
 <!-- ================================================== -->

 <nonterminal name="Goal" start="true"/>

 <nonterminal name="Statement"/>
 <nonterminal name="ThisIsStatement"/>
 <nonterminal name="TerminalStatement"/>
 <nonterminal name="MatchesStatement"/>
 <nonterminal name="ContextStatement"/>
 <nonterminal name="StartInStatement"/>
 <nonterminal name="IncludesStatement"/>
 <nonterminal name="NonterminalStatement"/>
 <nonterminal name="ReduceStatement"/>
 <nonterminal name="AcceptWhenStatement"/>
 <nonterminal name="PropertyStatement"/>
 <nonterminal name="StatementList"/>
 <nonterminal name="InstructionList"/>
 <nonterminal name="NonterminalList"/>
 <nonterminal name="IdentList"/>
 <nonterminal name="Instruction"/>

 <!-- ================================================== -->
 <!-- TERMINAL DEFINITIONS                               -->
 <!-- ================================================== -->

 <match terminal="COMMENT">
  <list>
   <char value="#"/>
   <closure>
    <class negated="true">
     <char value="&#x0A;"/>
     <char value="&#x0D;"/>
    </class>
   </closure>
   <union>
    <char value="&#x0A;"/>
    <string value="&#x0D;&#x0A;"/>
   </union>
  </list>
 </match>

 <match terminal="WHITESPACE">
  <positive-closure>
   <union>
    <char value="&#x09;"/>
    <char value="&#x0A;"/>
    <!-- <char value="&#x0B;"/> -->
    <char value="&#x0D;"/>
    <char value="&#x20;"/>
   </union>
  </positive-closure>
 </match>

 <match terminal="STRING">     
  <list>

   <string value="&quot;"/>

   <closure>
    <union>

     <class negated="true">
      <char value="&quot;"/>
      <char value="\"/>
     </class>

     <list>
      <char value="\"/>
      <class negated="true">
       <char value="&#x0A;"/>	
      </class>
     </list>

    </union>
   </closure>

   <string value="&quot;"/>

  </list>
 </match>

 <match terminal="IDENT">
  <list>
   <class>
    <char value="_"/>
    <interval lo="a" hi="z"/>
    <interval lo="A" hi="Z"/>
   </class>
   <closure>
    <class>
     <char value="-"/>
     <char value="_"/>
     <interval lo="a" hi="z"/>
     <interval lo="A" hi="Z"/>
     <interval lo="0" hi="9"/>
    </class>
   </closure>
  </list>
 </match>

 <match terminal="VERSION_STRING">
  <list>
   <positive-closure>
    <class>
     <interval lo="0" hi="9"/>
    </class>
   </positive-closure>
   <char value="."/>
   <positive-closure>
    <class>
     <interval lo="0" hi="9"/>
    </class>
   </positive-closure>
   <char value="."/>
   <positive-closure>
    <class>
     <interval lo="0" hi="9"/>
    </class>
   </positive-closure>
  </list>
 </match>

 <match terminal="COMMA">  <char value=","/> </match>
 <match terminal="SEMI">   <char value=";"/> </match>
 <match terminal="EQUALS"> <char value="="/> </match>

 <!-- ================================================== -->
 <!-- NONTERMINAL DEFINITIONS                            -->
 <!-- ================================================== -->

 <reduce nonterminal="Goal">
  <symbol name="ThisIsStatement"/>
  <symbol name="StatementList"/>
 </reduce>

 <reduce nonterminal="StatementList">
  <symbol name="Statement"/>
 </reduce>
 <reduce nonterminal="StatementList">
  <symbol name="StatementList"/>
  <symbol name="Statement"/>
 </reduce>

 <reduce nonterminal="Statement">
  <symbol name="TerminalStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="MatchesStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="ContextStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="StartInStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="IncludesStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="NonterminalStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="ReduceStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="AcceptWhenStatement"/>
 </reduce>
 <reduce nonterminal="Statement">
  <symbol name="PropertyStatement"/>
 </reduce>

 <reduce nonterminal="ThisIsStatement">
  <symbol name="THIS"/>
  <symbol name="IS"/>
  <symbol name="IDENT"/>
  <symbol name="VERSION"/>
  <symbol name="VERSION_STRING"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="TerminalStatement">
  <symbol name="TERMINAL"/>
  <symbol name="IdentList"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="MatchesStatement">
  <symbol name="IDENT"/>
  <symbol name="MATCHES"/>
  <symbol name="STRING"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="NonterminalStatement">
  <symbol name="NONTERMINAL"/>
  <symbol name="IdentList"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="ContextStatement">
  <symbol name="CONTEXT"/>
  <symbol name="IdentList"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="StartInStatement">
  <symbol name="START"/>
  <symbol name="IN"/>
  <symbol name="CONTEXT"/>
  <symbol name="IDENT"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="IncludesStatement">
  <symbol name="IDENT"/>
  <symbol name="INCLUDES"/>
  <symbol name="InstructionList"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="ReduceStatement">
  <symbol name="REDUCE"/>
  <symbol name="IDENT"/>
  <symbol name="WHEN"/>
  <symbol name="NonterminalList"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="AcceptWhenStatement">
  <symbol name="ACCEPT"/>
  <symbol name="WHEN"/>
  <symbol name="IDENT"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="PropertyStatement">
  <symbol name="PROPERTY"/>
  <symbol name="IDENT"/>
  <symbol name="EQUALS"/>
  <symbol name="STRING"/>
  <symbol name="SEMI"/>
 </reduce>

 <reduce nonterminal="IdentList">
  <symbol name="IDENT"/>
 </reduce>
 <reduce nonterminal="IdentList">
  <symbol name="IdentList"/>
  <symbol name="COMMA"/>
  <symbol name="IDENT"/>
 </reduce>

 <reduce nonterminal="NonterminalList">
  <symbol name="IDENT"/>
 </reduce>
 <reduce nonterminal="NonterminalList">
  <symbol name="NonterminalList"/>
  <symbol name="IDENT"/>
 </reduce>

 <reduce nonterminal="InstructionList">
  <symbol name="Instruction"/>
 </reduce>
 <reduce nonterminal="InstructionList">
  <symbol name="InstructionList"/>
  <symbol name="COMMA"/>
  <symbol name="Instruction"/>
 </reduce>

 <reduce nonterminal="Instruction">
  <symbol name="IDENT"/>
 </reduce>
 <reduce nonterminal="Instruction">
  <symbol name="IDENT"/>
  <symbol name="SHIFTS"/>
  <symbol name="IDENT"/>
 </reduce>
 <reduce nonterminal="Instruction">
  <symbol name="IDENT"/>
  <symbol name="UNSHIFTS"/>
 </reduce>

</grammar>
